name: Check if pkg.yaml and registry.yaml exist
description: Check if pkg.yaml and registry.yaml exist
runs:
  using: composite
  steps:
    - run: |
        if ! diff <(find pkgs -name registry.yaml -print0 | xargs -0 dirname | sort -u) <(find pkgs -name pkg.yaml -print0 | xargs -0 dirname | sort -u); then
          echo "" >&2
          echo "::error::Either pkg.yaml or registry.yaml isn't found. Don't forget to add pkg.yaml for test" >&2
          exit 1
        fi
      shell: bash
