name: Check if registry.yaml is updated
description: Check if pkg.yaml and registry.yaml exist
runs:
  using: composite
  steps:
    - run: aqua gr
      shell: bash
    - run: git add .
      shell: bash
    - run: git --no-pager diff --cached
      shell: bash
    - run: |
        if ! git diff --cached --exit-code; then
          echo "Please run 'aqua gr'" >&2
          echo "::error file=registry.yaml,title=Please run 'aqua gr'::"
          exit 1
        fi
      shell: bash
