name: Validate registry.yaml with JSON Schema
description: Validate registry.yaml with JSON Schema
inputs:
  ref:
    description: JSON Schema Ref
    required: false
    default: "main"
runs:
  using: composite
  steps:
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: "24"

    - run: curl --fail -O -L "https://raw.githubusercontent.com/aquaproj/aqua/${{inputs.ref}}/json-schema/registry.json"
      shell: bash
    - run: npm install --location=global ajv-cli ajv-formats
      shell: bash
    - run: ajv --spec=draft2020 -c ajv-formats -s registry.json -d registry.yaml
      shell: bash
