name: Validate registry.yaml with JSON Schema
description: Validate registry.yaml with JSON Schema
inputs:
  ref:
    description: JSON Schema Ref
    required: false
    default: "main"
runs:
  using: composite
  steps:
    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version: "16"

    - run: curl --fail -O -L "https://raw.githubusercontent.com/aquaproj/aqua/${{inputs.ref}}/json-schema/registry.json"
      shell: bash
    - run: npm install --location=global ajv-cli
      shell: bash
    - run: ajv --spec=draft2020 -s registry.json -d registry.yaml
      shell: bash
