---
name: actionlint
on:
  push:
    branches: [main]
    paths:
      - .github/**
  pull_request:
    branches: [main]
    paths:
      - .github/**
jobs:
  actionlint:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@1af1919efef445ad960f5ab4cf370e47e961d721 # v2.0.0
    with:
      aqua_version: v2.45.1
    permissions:
      pull-requests: write
      contents: read
