---
name: prettier
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - run: npm i -g prettier
      - run: prettier -c .
