---
name: prettier
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  prettier:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - run: npm i -g prettier
      - run: prettier -c .
