---
name: prettier
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - run: npm i -g prettier
      - run: prettier -c .
