---
name: prettier
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - run: npm i -g prettier
      - run: prettier -c .
