name: renovate-config-validator

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - renovate.json5
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - renovate.json5

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@b7cd2b598bb51d071a2474e98f55cc25f91abec1 # v0.1.3
