---
name: prettier
on: workflow_call
jobs:
  prettier:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: npm i -g prettier
      - run: prettier -c .
